EPS: ["EPS", "Eastern Pacific Shipping"]
PIL: ["PIL", "Pacific International Lines"]
OLDENDORFF: ["OLDENDORFF", "OLDENDORF", "OLDENDORFF CARRIERS"]
SUNRISE: ["SUNRISE", "SUN RISE", "SUNRISE BUNKERING"]
CISA: ["CISA"]
STELIOS Y: ["STELIOS Y", "STELIOS"]
SEAWAVE: ["SEAWAVE", "SEA WAVE"]
TRAFIGURA: ["TRAFIGURA", "TRAFIG"]
VITOL: ["VITOL"]
SHELL: ["SHELL"]
